services:
  - type: web
    name: she360
    env: python
    region: singapore
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /healthz
    autoDeploy: false